#!/bin/bash

# Constants
PNPM_VERSION=10.11.0

# Install all dependencies
brew bundle

# Create symlinks using stow
stow .

# Apply system settings
./system-settings/appearance.sh
./system-settings/hotkeys.sh

# Install pnpm
curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=$PNPM_VERSION sh -
